### ISSUE TITLE
Address all warnings in the code

### ISSUE THREAD

**Issue by greenozon** [Luca1991/DiscCheckEmu#18]
Currently there are some, eg:

```
4>C:\Dev\re\DiscCheckEmu\DiscCheckEmuAPIHook\APIHook.cpp(89,27): warning C4245: 'argument': conversion from 'int' to 'UINT', signed/unsigned mismatch
4>C:\Dev\re\DiscCheckEmu\DiscCheckEmuAPIHook\APIHook.cpp(100,27): warning C4245: 'argument': conversion from 'int' to 'UINT', signed/unsigned mismatch
4>C:\Dev\re\DiscCheckEmu\DiscCheckEmuAPIHook\APIHook.cpp(115,27): warning C4245: 'argument': conversion from 'int' to 'UINT', signed/unsigned mismatch
4>C:\Dev\re\DiscCheckEmu\DiscCheckEmuAPIHook\APIHook.cpp(78,13): warning C4996: 'freopen': This function or variable may be unsafe. Consider using freopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
4>C:\Dev\re\DiscCheckEmu\DiscCheckEmuAPIHook\APIHook.cpp(69,61): warning C4100: 'reserved': unreferenced formal parameter
4>C:\Dev\re\DiscCheckEmu\DiscCheckEmuAPIHook\APIHook.cpp(69,31): warning C4100: 'hinst': unreferenced formal parameter
```

PR:  https://github.com/Luca1991/DiscCheckEmu/pull/19

**Comment by greenozon** [comment]
Not sure about freopen -> freopen_s.... 
any ideas? :)

**Comment by Luca1991** [comment]
I think that many of these warnings are now fixed due to PR #19 , right? 
I'm going to have a look atthe freopen issue.

Since you are at it, can you add the w4 warning in the cmake? something like this should be ok:

`target_compile_options(${PROJECT_NAME} PRIVATE /W4 /WX)`

thanks

**Comment by Luca1991** [comment]
That's the next thing I'm going to look at.

**Comment by Luca1991** [comment]
All the warnings should be fixed now (#b71b4fb).

**Comment by greenozon** [comment]
Great stuff!
but I still see 2 warnings!

lets fix'em  all? :)


```
4>RegUtils.cpp
4>C:\Dev\DiscCheckEmu\DiscCheckEmuAPIHook\Util\RegUtils.cpp(51,117): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
4>C:\Dev\DiscCheckEmu\DiscCheckEmuAPIHook\Util\RegUtils.cpp(53,116): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
```

**Comment by Luca1991** [comment]
Thanks @greenozon , issue reopened.

I don't know why but I can't see these warnings on my build logs even with ```target_compile_options(${PROJECT_NAME} PRIVATE /W4)```.

I'll fix it tomorrow.

**Comment by Luca1991** [comment]
Hi @greenozon since I can't reproduce your warnings, can you plese tell me:
* What version of MSVC are you using
* What build type are you using (x86/x64)
* What's your Windows version

Thanks a lot

**Comment by greenozon** [comment]
WOW! it looks crystal clear now!

note:

how about treating last issue? :)

```
1>CMake Deprecation Warning at _deps/yaml-cpp-src/CMakeLists.txt:2 (cmake_minimum_required):
1>  Compatibility with CMake < 3.5 will be removed from a future version of
1>  CMake.
1>
1>  Update the VERSION argument <min> value or use a ...<max> suffix to tell
1>  CMake that the project does not need compatibility with older versions.
```

**Comment by Luca1991** [comment]
Hi @greenozon 
thank you for your feedback.

The warning you get is from yaml-cpp, a dependency of this project, so it's not fixable on my end.

Let me know if I can close this issue, thanks :)

**Comment by greenozon** [comment]
OK, makes sense
thanks for support!
cu next time!
